-- MySQL 8 read-only validation. Run after 06. All samples are restricted to SIM20260918 prefix.
-- Snapshot date is fixed; do not use CURDATE() to shift cohort meaning.
SET @snapshot_date = DATE('2026-09-18');
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT COUNT(*) AS row_count, COUNT(DISTINCT CUST_ID) AS distinct_ids,
SUM(CUR_POINT_AUM) AS total_aum, AVG(CUR_POINT_AUM) AS avg_aum,
MIN(CUR_POINT_AUM) AS min_aum, MAX(CUR_POINT_AUM) AS max_aum FROM b;
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%'), ranked AS (SELECT CUR_POINT_AUM, ROW_NUMBER() OVER(ORDER BY CUR_POINT_AUM) rn, COUNT(*) OVER() n FROM b)
SELECT AVG(CUR_POINT_AUM) AS median_aum FROM ranked WHERE rn IN (FLOOR((n+1)/2),FLOOR((n+2)/2));
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT CUST_ID FROM b WHERE
 ROUND(CUR_POINT_AUM,2) <> ROUND(CUR_DEPOSIT_BALANCE+CUR_WMP_BALANCE+CUR_FUND_BALANCE+CUR_GOLD_BALANCE+CUR_TREASURY_BOND_BALANCE+CUR_TRUST_BALANCE+CUR_VALUE_TYPE_INSURANCE_BALANCE,2)
 OR ROUND(CUR_DEPOSIT_BALANCE,2) <> ROUND(CUR_DEMAND_DEPOSIT_BALANCE+CUR_TIME_DEPOSIT_BALANCE,2)
 OR CUR_HOLDING_WMP_FLAG <> (CUR_WMP_BALANCE>0) OR CUR_HOLDING_FUND_FLAG <> (CUR_FUND_BALANCE>0);
-- Expected empty result above.
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT CUR_CUST_LEVEL, CUR_WMP_RISK_ASSESSMENT_LEVEL,
 COUNT(*) n, AVG(CUR_HOLDING_WMP_FLAG) wmp_rate, AVG(CUR_HOLDING_FUND_FLAG) fund_rate, AVG(((CUR_DEPOSIT_BALANCE>0)+(CUR_WMP_BALANCE>0)+(CUR_FUND_BALANCE>0)+(CUR_GOLD_BALANCE>0)+(CUR_TREASURY_BOND_BALANCE>0)+(CUR_TRUST_BALANCE>0)+(CUR_VALUE_TYPE_INSURANCE_BALANCE>0))) mean_product_types
 FROM b GROUP BY CUR_CUST_LEVEL,CUR_WMP_RISK_ASSESSMENT_LEVEL;
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT CUR_CORE_CM_LEVEL1_BRANCH,COUNT(*) n,SUM(CUR_POINT_AUM) aum,
 AVG(CUR_HOLDING_WMP_FLAG) wmp_rate,AVG(((CUR_DEPOSIT_BALANCE>0)+(CUR_WMP_BALANCE>0)+(CUR_FUND_BALANCE>0)+(CUR_GOLD_BALANCE>0)+(CUR_TREASURY_BOND_BALANCE>0)+(CUR_TRUST_BALANCE>0)+(CUR_VALUE_TYPE_INSURANCE_BALANCE>0))) mean_product_types FROM b GROUP BY CUR_CORE_CM_LEVEL1_BRANCH;
-- Golden cohort: cumulative DIFF-NAME interbank inflow, not all transfer inflow or single maximum.
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT CUST_ID,CUR_POINT_AUM,LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_AMT,
 CUR_DEPOSIT_BALANCE/NULLIF(CUR_POINT_AUM,0) deposit_ratio FROM b
 WHERE LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_AMT>=500000 AND CUR_HOLDING_WMP_FLAG=0
 AND CUR_WMP_RISK_ASSESSMENT_LEVEL IN ('C3','C4','C5');
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT COUNT(*) n,SUM(NEXT_TIME_DEPOSIT_LATEST_MATURITY_AMT) nearest_maturity_amount
 FROM b WHERE NEXT_TIME_DEPOSIT_LATEST_MAT_DATE>@snapshot_date AND NEXT_TIME_DEPOSIT_LATEST_MAT_DATE<=DATE_ADD(@snapshot_date,INTERVAL 30 DAY)
 AND NEXT_TIME_DEPOSIT_LATEST_MATURITY_AMT>=100000;
-- This is nearest recorded maturity, not all future 30-day maturities.
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT COUNT(*) n,AVG(CUR_MONTH_APP_LOGIN_DAYS/18.0) current_daily_login_rate,
 AVG(PREV_3_MONTHS_APP_LOGIN_DAYS/92.0) prior_daily_login_rate FROM b
 WHERE LAST_MONTH_PAYROLL_AMT>0 AND CUR_MONTH_PAYROLL_AMT<LAST_MONTH_PAYROLL_AMT*0.7
 AND LAST_MONTH_PAYROLL_AMT<PREV_6_MONTHS_AVG_PAYROLL_AMT*0.85;
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%') SELECT COUNT(*) n,SUM(CUR_POINT_AUM) aum FROM b
 WHERE CUR_POINT_AUM>=1000000 AND ((CUR_DEPOSIT_BALANCE>0)+(CUR_WMP_BALANCE>0)+(CUR_FUND_BALANCE>0)+(CUR_GOLD_BALANCE>0)+(CUR_TREASURY_BOND_BALANCE>0)+(CUR_TRUST_BALANCE>0)+(CUR_VALUE_TYPE_INSURANCE_BALANCE>0))<=2;
-- All results should be 0; NULL is allowed and not treated as invalid.
SELECT 'REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG' AND m.tag_code=CAST(b.`REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG` AS CHAR))
UNION ALL
SELECT 'DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG' AND m.tag_code=CAST(b.`DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_MOBILE_NUMBER_NORMAL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_MOBILE_NUMBER_NORMAL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_MOBILE_NUMBER_NORMAL_FLAG' AND m.tag_code=CAST(b.`CUR_MOBILE_NUMBER_NORMAL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_OUR_BANK_EMPLOYEE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_OUR_BANK_EMPLOYEE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_OUR_BANK_EMPLOYEE_FLAG' AND m.tag_code=CAST(b.`CUR_OUR_BANK_EMPLOYEE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_MOBILE_DIGIT_STANDARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_MOBILE_DIGIT_STANDARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_MOBILE_DIGIT_STANDARD_FLAG' AND m.tag_code=CAST(b.`CUR_MOBILE_DIGIT_STANDARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_PRESTIGE_CARD_A_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_PRESTIGE_CARD_A_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_PRESTIGE_CARD_A_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_PRESTIGE_CARD_A_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ONLINE_PAY_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ONLINE_PAY_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ONLINE_PAY_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_YOUTH_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_YOUTH_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_YOUTH_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_YOUTH_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_DIRECT_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_DIRECT_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_DIRECT_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_DIRECT_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_WMP_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_WMP_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_WMP_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_WMP_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_CC_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_CC_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_CC_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_CC_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_CLASS_1_ACCT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_CLASS_1_ACCT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_CLASS_1_ACCT_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_CLASS_1_ACCT_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_PRESTIGE_CARD_B_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_PRESTIGE_CARD_B_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_PRESTIGE_CARD_B_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_PRESTIGE_CARD_B_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_PAY_LOAN_B_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_PAY_LOAN_B_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_PAY_LOAN_B_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_PAY_LOAN_B_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_PAY_LOAN_A_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_PAY_LOAN_A_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_PAY_LOAN_A_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_PAY_LOAN_A_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_TREASURY_BOND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_TREASURY_BOND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_TREASURY_BOND_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_TREASURY_BOND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VIP_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VIP_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VIP_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VIP_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_TRADE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_TRADE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_TRADE_LOAN_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_TRADE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_SS_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_SS_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_SS_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_SS_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_RESERVE_FUND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_RESERVE_FUND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_RESERVE_FUND_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_RESERVE_FUND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_WMP_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_WMP_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_WMP_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_WMP_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_ONLINE_PAY_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_ONLINE_PAY_LOAN_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_ONLINE_PAY_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_TIME_DEPOSIT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_TIME_DEPOSIT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_TIME_DEPOSIT_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_TIME_DEPOSIT_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_CC_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_CC_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_CC_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_CC_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_PLEDGE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_PLEDGE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_PLEDGE_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_PLEDGE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_TREASURY_BOND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_TREASURY_BOND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_TREASURY_BOND_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_TREASURY_BOND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_TRUST_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_TRUST_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_TRUST_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_TRUST_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG' AND m.tag_code=CAST(b.`CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_PP_ACCT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_PP_ACCT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_PP_ACCT_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_PP_ACCT_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_GOLD_LEVEL_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_GOLD_LEVEL_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_GOLD_LEVEL_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_GOLD_LEVEL_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_GOLD_ACCUMULATION_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_GOLD_ACCUMULATION_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_GOLD_ACCUMULATION_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_GOLD_ACCUMULATION_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ANNUITY_INSURANCE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ANNUITY_INSURANCE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ANNUITY_INSURANCE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ANNUITY_INSURANCE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_FUND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_FUND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_FUND_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_FUND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_HEALTH_INSURANCE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_HEALTH_INSURANCE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_HEALTH_INSURANCE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_HEALTH_INSURANCE_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_CASH_MGMT_WMP_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_CASH_MGMT_WMP_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_CASH_MGMT_WMP_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_CASH_MGMT_WMP_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_EASY_FINANCE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_EASY_FINANCE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_EASY_FINANCE_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_EASY_FINANCE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_ONLINE_GOLD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_ONLINE_GOLD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_ONLINE_GOLD_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_ONLINE_GOLD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ACCT_GOLD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ACCT_GOLD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ACCT_GOLD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ACCT_GOLD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_OTC_BOND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_OTC_BOND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_OTC_BOND_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_OTC_BOND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG' AND m.tag_code=CAST(b.`CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_CASH_ASSET_OVER_ALLOCATED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CASH_ASSET_OVER_ALLOCATED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CASH_ASSET_OVER_ALLOCATED_FLAG' AND m.tag_code=CAST(b.`CUR_CASH_ASSET_OVER_ALLOCATED_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_SUPREME_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_SUPREME_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_SUPREME_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_SUPREME_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_PRIVATE_BANK_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_PRIVATE_BANK_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_PRIVATE_BANK_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_PRIVATE_BANK_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_TIME_DEPOSIT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_TIME_DEPOSIT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_TIME_DEPOSIT_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_TIME_DEPOSIT_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_FX_WMP_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_FX_WMP_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_FX_WMP_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_FX_WMP_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_TEACHER_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_TEACHER_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_TEACHER_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_TEACHER_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_GOLD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_GOLD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_GOLD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_GOLD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_BUSINESS_LINK_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_BUSINESS_LINK_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_BUSINESS_LINK_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_BUSINESS_LINK_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_HOLDING_DIY_DEBIT_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_HOLDING_DIY_DEBIT_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_HOLDING_DIY_DEBIT_CARD_FLAG' AND m.tag_code=CAST(b.`CUR_HOLDING_DIY_DEBIT_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG' AND m.tag_code=CAST(b.`CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_FUND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_FUND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_FUND_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_FUND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG' AND m.tag_code=CAST(b.`CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_HOLDING_PRESTIGE_CARD_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_HOLDING_PRESTIGE_CARD_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_HOLDING_PRESTIGE_CARD_FLAG' AND m.tag_code=CAST(b.`HIST_HOLDING_PRESTIGE_CARD_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_MOBILE_BANKING_OPENED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_MOBILE_BANKING_OPENED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_MOBILE_BANKING_OPENED_FLAG' AND m.tag_code=CAST(b.`CUR_MOBILE_BANKING_OPENED_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_CARE_CUST_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CARE_CUST_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CARE_CUST_FLAG' AND m.tag_code=CAST(b.`CUR_CARE_CUST_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG' AND m.tag_code=CAST(b.`HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_OUR_BANK_LOAN_OVERDUE_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_OUR_BANK_LOAN_OVERDUE_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_OUR_BANK_LOAN_OVERDUE_FLAG' AND m.tag_code=CAST(b.`CUR_OUR_BANK_LOAN_OVERDUE_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_AML_BLACKLIST_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_AML_BLACKLIST_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_AML_BLACKLIST_FLAG' AND m.tag_code=CAST(b.`CUR_AML_BLACKLIST_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_MARKETING_BLACKLIST_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_MARKETING_BLACKLIST_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_MARKETING_BLACKLIST_FLAG' AND m.tag_code=CAST(b.`CUR_MARKETING_BLACKLIST_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_TO_DORMANT_ACCT_WARNING_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_TO_DORMANT_ACCT_WARNING_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_TO_DORMANT_ACCT_WARNING_FLAG' AND m.tag_code=CAST(b.`CUR_TO_DORMANT_ACCT_WARNING_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG' AND m.tag_code=CAST(b.`CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_CUST_LEVEL_SMART_SUSPEND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CUST_LEVEL_SMART_SUSPEND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CUST_LEVEL_SMART_SUSPEND_FLAG' AND m.tag_code=CAST(b.`CUR_CUST_LEVEL_SMART_SUSPEND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_WARNING_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WARNING_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WARNING_FLAG' AND m.tag_code=CAST(b.`CUR_WARNING_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_TO_SMART_SUSPEND_WARNING_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_TO_SMART_SUSPEND_WARNING_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_TO_SMART_SUSPEND_WARNING_FLAG' AND m.tag_code=CAST(b.`CUR_TO_SMART_SUSPEND_WARNING_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG' AND m.tag_code=CAST(b.`CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_PB_VIP_POTENTIAL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PB_VIP_POTENTIAL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PB_VIP_POTENTIAL_FLAG' AND m.tag_code=CAST(b.`CUR_PB_VIP_POTENTIAL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG' AND m.tag_code=CAST(b.`CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG' AND m.tag_code=CAST(b.`CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION' AND m.tag_code=CAST(b.`CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION` AS CHAR))
UNION ALL
SELECT 'CUR_WECOM_AUTH_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WECOM_AUTH_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WECOM_AUTH_FLAG' AND m.tag_code=CAST(b.`CUR_WECOM_AUTH_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG' AND m.tag_code=CAST(b.`CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG' AND m.tag_code=CAST(b.`CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG' AND m.tag_code=CAST(b.`CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022' AND m.tag_code=CAST(b.`CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022` AS CHAR))
UNION ALL
SELECT 'HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG' AND m.tag_code=CAST(b.`HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG` AS CHAR))
UNION ALL
SELECT 'LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AND m.tag_code=CAST(b.`LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_BENEFIT_VALUE_ACTIVATION_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_BENEFIT_VALUE_ACTIVATION_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_BENEFIT_VALUE_ACTIVATION_STATUS' AND m.tag_code=CAST(b.`CUR_BENEFIT_VALUE_ACTIVATION_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_SALARY_TREASURE_2_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_SALARY_TREASURE_2_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_SALARY_TREASURE_2_FLAG' AND m.tag_code=CAST(b.`CUR_YEAR_SALARY_TREASURE_2_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_SALARY_LINK_PAYROLL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_SALARY_LINK_PAYROLL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_SALARY_LINK_PAYROLL_FLAG' AND m.tag_code=CAST(b.`CUR_YEAR_SALARY_LINK_PAYROLL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_WEALTH_REFERRAL_M1_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WEALTH_REFERRAL_M1_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WEALTH_REFERRAL_M1_FLAG' AND m.tag_code=CAST(b.`CUR_WEALTH_REFERRAL_M1_FLAG` AS CHAR))
UNION ALL
SELECT 'HIST_SALARY_LINK_PAYROLL_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_SALARY_LINK_PAYROLL_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_SALARY_LINK_PAYROLL_FLAG' AND m.tag_code=CAST(b.`HIST_SALARY_LINK_PAYROLL_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AND m.tag_code=CAST(b.`CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024` AS CHAR))
UNION ALL
SELECT 'CUR_WEALTH_REFERRAL_M2_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WEALTH_REFERRAL_M2_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WEALTH_REFERRAL_M2_FLAG' AND m.tag_code=CAST(b.`CUR_WEALTH_REFERRAL_M2_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AND m.tag_code=CAST(b.`CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024` AS CHAR))
UNION ALL
SELECT 'CUR_PERS_LOAN_PROMOTER_M2_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PERS_LOAN_PROMOTER_M2_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PERS_LOAN_PROMOTER_M2_FLAG' AND m.tag_code=CAST(b.`CUR_PERS_LOAN_PROMOTER_M2_FLAG` AS CHAR))
UNION ALL
SELECT 'LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AND m.tag_code=CAST(b.`LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG` AS CHAR))
UNION ALL
SELECT 'LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AND m.tag_code=CAST(b.`LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG` AS CHAR))
UNION ALL
SELECT 'LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AND m.tag_code=CAST(b.`LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG' AND m.tag_code=CAST(b.`CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG` AS CHAR))
UNION ALL
SELECT 'LAST_12_MONTHS_LARGE_TRANSFER_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_12_MONTHS_LARGE_TRANSFER_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_12_MONTHS_LARGE_TRANSFER_FLAG' AND m.tag_code=CAST(b.`LAST_12_MONTHS_LARGE_TRANSFER_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_WEALTH_PROMOTER_VALID_M2_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WEALTH_PROMOTER_VALID_M2_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WEALTH_PROMOTER_VALID_M2_FLAG' AND m.tag_code=CAST(b.`CUR_WEALTH_PROMOTER_VALID_M2_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN' AND m.tag_code=CAST(b.`CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN` AS CHAR))
UNION ALL
SELECT 'HIST_WECOM_FRIEND_ADDED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_WECOM_FRIEND_ADDED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_WECOM_FRIEND_ADDED_FLAG' AND m.tag_code=CAST(b.`HIST_WECOM_FRIEND_ADDED_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_WECOM_GROUP_JOINED_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WECOM_GROUP_JOINED_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WECOM_GROUP_JOINED_FLAG' AND m.tag_code=CAST(b.`CUR_WECOM_GROUP_JOINED_FLAG` AS CHAR))
UNION ALL
SELECT 'CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG' AND m.tag_code=CAST(b.`CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG` AS CHAR))
UNION ALL
SELECT 'GENDER' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`GENDER` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='GENDER' AND m.tag_code=CAST(b.`GENDER` AS CHAR))
UNION ALL
SELECT 'ID_TYPE' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`ID_TYPE` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='ID_TYPE' AND m.tag_code=CAST(b.`ID_TYPE` AS CHAR))
UNION ALL
SELECT 'OUTSIDE_ASSET_WAN_KYC' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`OUTSIDE_ASSET_WAN_KYC` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='OUTSIDE_ASSET_WAN_KYC' AND m.tag_code=CAST(b.`OUTSIDE_ASSET_WAN_KYC` AS CHAR))
UNION ALL
SELECT 'OUTSIDE_ASSET_OPS_KYC' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`OUTSIDE_ASSET_OPS_KYC` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='OUTSIDE_ASSET_OPS_KYC' AND m.tag_code=CAST(b.`OUTSIDE_ASSET_OPS_KYC` AS CHAR))
UNION ALL
SELECT 'OUTSIDE_ASSET_PB_KYC' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`OUTSIDE_ASSET_PB_KYC` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='OUTSIDE_ASSET_PB_KYC' AND m.tag_code=CAST(b.`OUTSIDE_ASSET_PB_KYC` AS CHAR))
UNION ALL
SELECT 'HOUSEHOLD_ANNUAL_INCOME_PB_KYC' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HOUSEHOLD_ANNUAL_INCOME_PB_KYC` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HOUSEHOLD_ANNUAL_INCOME_PB_KYC' AND m.tag_code=CAST(b.`HOUSEHOLD_ANNUAL_INCOME_PB_KYC` AS CHAR))
UNION ALL
SELECT 'CUR_APP_DEVICE_TYPE' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_APP_DEVICE_TYPE` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_APP_DEVICE_TYPE' AND m.tag_code=CAST(b.`CUR_APP_DEVICE_TYPE` AS CHAR))
UNION ALL
SELECT 'HIGHEST_EDUCATION' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIGHEST_EDUCATION` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIGHEST_EDUCATION' AND m.tag_code=CAST(b.`HIGHEST_EDUCATION` AS CHAR))
UNION ALL
SELECT 'PREV_12_MONTHS_MAX_CUST_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`PREV_12_MONTHS_MAX_CUST_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='PREV_12_MONTHS_MAX_CUST_LEVEL' AND m.tag_code=CAST(b.`PREV_12_MONTHS_MAX_CUST_LEVEL` AS CHAR))
UNION ALL
SELECT 'CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION' AND m.tag_code=CAST(b.`CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION` AS CHAR))
UNION ALL
SELECT 'HIST_MAX_CUST_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_MAX_CUST_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_MAX_CUST_LEVEL' AND m.tag_code=CAST(b.`HIST_MAX_CUST_LEVEL` AS CHAR))
UNION ALL
SELECT 'CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL' AND m.tag_code=CAST(b.`CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL` AS CHAR))
UNION ALL
SELECT 'CUR_PB_CUST_TYPE' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PB_CUST_TYPE` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PB_CUST_TYPE' AND m.tag_code=CAST(b.`CUR_PB_CUST_TYPE` AS CHAR))
UNION ALL
SELECT 'CUR_CUST_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CUST_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CUST_LEVEL' AND m.tag_code=CAST(b.`CUR_CUST_LEVEL` AS CHAR))
UNION ALL
SELECT 'LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AND m.tag_code=CAST(b.`LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS` AS CHAR))
UNION ALL
SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS' AND m.tag_code=CAST(b.`CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS` AS CHAR))
UNION ALL
SELECT 'CUR_EXCLUSIVE_MEMBER_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_EXCLUSIVE_MEMBER_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_EXCLUSIVE_MEMBER_LEVEL' AND m.tag_code=CAST(b.`CUR_EXCLUSIVE_MEMBER_LEVEL` AS CHAR))
UNION ALL
SELECT 'LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AND m.tag_code=CAST(b.`LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS` AS CHAR))
UNION ALL
SELECT 'LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AND m.tag_code=CAST(b.`LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS` AS CHAR))
UNION ALL
SELECT 'CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AND m.tag_code=CAST(b.`CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS` AS CHAR))
UNION ALL
SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026' AND m.tag_code=CAST(b.`CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026` AS CHAR))
UNION ALL
SELECT 'CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY' AND m.tag_code=CAST(b.`CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY` AS CHAR))
UNION ALL
SELECT 'CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL' AND m.tag_code=CAST(b.`CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL` AS CHAR))
UNION ALL
SELECT 'CUR_FUND_SIP_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FUND_SIP_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FUND_SIP_STATUS' AND m.tag_code=CAST(b.`CUR_FUND_SIP_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_BENEFIT_VALUE_ACCT_TYPE' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_BENEFIT_VALUE_ACCT_TYPE` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_BENEFIT_VALUE_ACCT_TYPE' AND m.tag_code=CAST(b.`CUR_BENEFIT_VALUE_ACCT_TYPE` AS CHAR))
UNION ALL
SELECT 'CUR_BUSINESS_LINK_CREDIT_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_BUSINESS_LINK_CREDIT_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_BUSINESS_LINK_CREDIT_STATUS' AND m.tag_code=CAST(b.`CUR_BUSINESS_LINK_CREDIT_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_PAY_LOAN_TYPE_CREDIT_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PAY_LOAN_TYPE_CREDIT_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PAY_LOAN_TYPE_CREDIT_STATUS' AND m.tag_code=CAST(b.`CUR_PAY_LOAN_TYPE_CREDIT_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS' AND m.tag_code=CAST(b.`CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_FAST_LOAN_CREDIT_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FAST_LOAN_CREDIT_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FAST_LOAN_CREDIT_STATUS' AND m.tag_code=CAST(b.`CUR_FAST_LOAN_CREDIT_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS' AND m.tag_code=CAST(b.`CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE' AND m.tag_code=CAST(b.`CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE` AS CHAR))
UNION ALL
SELECT 'CUR_WMP_RISK_ASSESSMENT_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WMP_RISK_ASSESSMENT_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WMP_RISK_ASSESSMENT_LEVEL' AND m.tag_code=CAST(b.`CUR_WMP_RISK_ASSESSMENT_LEVEL` AS CHAR))
UNION ALL
SELECT 'CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL' AND m.tag_code=CAST(b.`CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL` AS CHAR))
UNION ALL
SELECT 'CUR_BUSINESS_LINK_A_CARD_RATING' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_BUSINESS_LINK_A_CARD_RATING` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_BUSINESS_LINK_A_CARD_RATING' AND m.tag_code=CAST(b.`CUR_BUSINESS_LINK_A_CARD_RATING` AS CHAR))
UNION ALL
SELECT 'CUR_PAY_LOAN_A_CARD_RATING' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PAY_LOAN_A_CARD_RATING` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PAY_LOAN_A_CARD_RATING' AND m.tag_code=CAST(b.`CUR_PAY_LOAN_A_CARD_RATING` AS CHAR))
UNION ALL
SELECT 'CUR_PAY_LOAN_B_CARD_RATING' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_PAY_LOAN_B_CARD_RATING` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_PAY_LOAN_B_CARD_RATING' AND m.tag_code=CAST(b.`CUR_PAY_LOAN_B_CARD_RATING` AS CHAR))
UNION ALL
SELECT 'INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT' AND m.tag_code=CAST(b.`INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT` AS CHAR))
UNION ALL
SELECT 'CUR_FAST_LOAN_B_CARD_RATING' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FAST_LOAN_B_CARD_RATING` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FAST_LOAN_B_CARD_RATING' AND m.tag_code=CAST(b.`CUR_FAST_LOAN_B_CARD_RATING` AS CHAR))
UNION ALL
SELECT 'CUR_FUND_RISK_ASSESSMENT_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_FUND_RISK_ASSESSMENT_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_FUND_RISK_ASSESSMENT_LEVEL' AND m.tag_code=CAST(b.`CUR_FUND_RISK_ASSESSMENT_LEVEL` AS CHAR))
UNION ALL
SELECT 'HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT' AND m.tag_code=CAST(b.`HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT` AS CHAR))
UNION ALL
SELECT 'CUR_INSURANCE_RISK_ASSESSMENT_LEVEL' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_INSURANCE_RISK_ASSESSMENT_LEVEL` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_INSURANCE_RISK_ASSESSMENT_LEVEL' AND m.tag_code=CAST(b.`CUR_INSURANCE_RISK_ASSESSMENT_LEVEL` AS CHAR))
UNION ALL
SELECT 'LATEST_CIR_EMPLOYMENT_STATUS' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`LATEST_CIR_EMPLOYMENT_STATUS` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='LATEST_CIR_EMPLOYMENT_STATUS' AND m.tag_code=CAST(b.`LATEST_CIR_EMPLOYMENT_STATUS` AS CHAR))
UNION ALL
SELECT 'CUR_CORE_CM_LEVEL1_BRANCH' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CORE_CM_LEVEL1_BRANCH` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CORE_CM_LEVEL1_BRANCH' AND m.tag_code=CAST(b.`CUR_CORE_CM_LEVEL1_BRANCH` AS CHAR))
UNION ALL
SELECT 'ACCT_OPENING_LEVEL1_BRANCH' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`ACCT_OPENING_LEVEL1_BRANCH` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='ACCT_OPENING_LEVEL1_BRANCH' AND m.tag_code=CAST(b.`ACCT_OPENING_LEVEL1_BRANCH` AS CHAR))
UNION ALL
SELECT 'CUR_CORE_CM_LEVEL2_BRANCH' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CORE_CM_LEVEL2_BRANCH` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CORE_CM_LEVEL2_BRANCH' AND m.tag_code=CAST(b.`CUR_CORE_CM_LEVEL2_BRANCH` AS CHAR))
UNION ALL
SELECT 'ACCT_OPENING_LEVEL2_BRANCH' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`ACCT_OPENING_LEVEL2_BRANCH` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='ACCT_OPENING_LEVEL2_BRANCH' AND m.tag_code=CAST(b.`ACCT_OPENING_LEVEL2_BRANCH` AS CHAR))
UNION ALL
SELECT 'HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH' AND m.tag_code=CAST(b.`HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH` AS CHAR))
UNION ALL
SELECT 'CUR_CORE_CM_LEVEL3_BRANCH' field_name, COUNT(*) invalid_count FROM `indiv_cust`.`L_INDVCST_LABEL` b WHERE CUST_ID LIKE 'SIM20260918%' AND b.`CUR_CORE_CM_LEVEL3_BRANCH` IS NOT NULL AND NOT EXISTS (SELECT 1 FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` m WHERE m.tag_name_en='CUR_CORE_CM_LEVEL3_BRANCH' AND m.tag_code=CAST(b.`CUR_CORE_CM_LEVEL3_BRANCH` AS CHAR));

-- Opportunity rule v1; derived output only, no base-table opportunity label.
WITH b AS (SELECT * FROM `indiv_cust`.`L_INDVCST_LABEL` WHERE CUST_ID LIKE 'SIM20260918%'), components AS (
 SELECT b.*,
 LEAST(25,GREATEST(0,25*LOG10(1+CUR_POINT_AUM/10000)/LOG10(1001))) value_score,
 CASE WHEN LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_AMT>=500000 THEN 25
 WHEN NEXT_TIME_DEPOSIT_LATEST_MAT_DATE>@snapshot_date AND NEXT_TIME_DEPOSIT_LATEST_MAT_DATE<=DATE_ADD(@snapshot_date,INTERVAL 30 DAY) AND NEXT_TIME_DEPOSIT_LATEST_MATURITY_AMT>=100000 THEN 18
 WHEN CUR_MONTH_PAYROLL_AMT>0 THEN 8 ELSE 0 END event_score,
 (CASE WHEN CUR_HOLDING_WMP_FLAG=0 THEN 20 WHEN CUR_WMP_BALANCE/NULLIF(CUR_POINT_AUM,0)<0.1 THEN 8 ELSE 0 END)
 +(CASE WHEN CUR_HOLDING_FUND_FLAG=0 AND CUR_WMP_RISK_ASSESSMENT_LEVEL IN ('C3','C4','C5') THEN 5 ELSE 0 END) gap_score,
 7*LEAST(1,CUR_YEAR_CARRIER_ACTIVITY_PARTICIPATION_COUNT)+3*(HIST_WECOM_PRODUCT_MSG_LATEST_CLICK_TIME_ONLINE_OPS IS NOT NULL) response_score,
 7*CUR_MOBILE_NUMBER_NORMAL_FLAG+5*CUR_WECOM_AUTH_FLAG+3*(LAST_30_DAYS_APP_LOGIN_DAYS>=4) reach_score,
 10*(LAST_7_DAYS_PHONE_FACE_VISIT_COUNT>=3)+5*(LAST_30_DAYS_APP_LOGIN_DAYS=0) penalty,
 (CUR_MARKETING_BLACKLIST_FLAG=1 OR DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG=1 OR CUR_AML_BLACKLIST_FLAG=1 OR CUR_CUST_LEVEL_SMART_SUSPEND_FLAG=1 OR CUR_OUR_BANK_LOAN_OVERDUE_FLAG=1 OR CUR_WMP_RISK_ASSESSMENT_LEVEL IS NULL OR CUR_WMP_RISK_ASSESSMENT_LEVEL='C1' OR (CUR_MOBILE_NUMBER_NORMAL_FLAG<>1 AND CUR_WECOM_AUTH_FLAG<>1)) excluded
 FROM b), scored AS (SELECT CUST_ID,excluded,ROUND(GREATEST(0,LEAST(100,value_score+event_score+gap_score+response_score+reach_score-penalty)),2) score FROM components)
 SELECT CASE WHEN excluded THEN 'EXCLUDED' WHEN score>=65 THEN 'HIGH' WHEN score>=40 THEN 'MEDIUM' ELSE 'LOW' END priority,COUNT(*) n FROM scored GROUP BY priority;
