-- ============================================================================
-- 99_validate_L_INDVCST_LABEL.sql
-- 用途      : 建表 + 导入码值之后的人工校验脚本
-- 重要      : 本脚本【纯查询】，不含 CREATE / ALTER / DROP / INSERT / UPDATE / DELETE
--            全部语句可直接执行，不改变任何数据
-- 目标库    : indiv_cust
-- 期望值    : 宽表 970 列（含主键 CUST_ID）；码表 6 列；码值 1723 条 / 177 个字段
--             布尔 129 字段 × 2 = 258 条；选项 48 字段；机构类 6 字段
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. 字段数量：两表列数与表结构是否与交付一致
--    期望：L_INDVCST_LABEL = 970 列；L_INDVCST_LABEL_CODE_MAP = 6 列
-- ----------------------------------------------------------------------------
SELECT 'L_INDVCST_LABEL' AS table_name, COUNT(*) AS column_count
  FROM information_schema.COLUMNS
 WHERE TABLE_SCHEMA = 'indiv_cust' AND TABLE_NAME = 'L_INDVCST_LABEL'
UNION ALL
SELECT 'L_INDVCST_LABEL_CODE_MAP', COUNT(*)
  FROM information_schema.COLUMNS
 WHERE TABLE_SCHEMA = 'indiv_cust' AND TABLE_NAME = 'L_INDVCST_LABEL_CODE_MAP';

-- 1b. 宽表标签字段数（不含主键）+ 英文字段名唯一性
--     期望：969 / 969
SELECT COUNT(*) AS tag_column_count,
       COUNT(DISTINCT COLUMN_NAME) AS distinct_column_count
  FROM information_schema.COLUMNS
 WHERE TABLE_SCHEMA = 'indiv_cust' AND TABLE_NAME = 'L_INDVCST_LABEL'
   AND COLUMN_NAME <> 'CUST_ID';

-- 1c. 宽表结构体检：超长列名 / 缺 COMMENT / 主键
--     期望：0 / 0 / 1
SELECT SUM(CHAR_LENGTH(COLUMN_NAME) > 64)                    AS over_64_char_columns,
       SUM(COLUMN_COMMENT = '' OR COLUMN_COMMENT IS NULL)     AS columns_without_comment,
       (SELECT COUNT(*) FROM information_schema.STATISTICS
         WHERE TABLE_SCHEMA='indiv_cust' AND TABLE_NAME='L_INDVCST_LABEL'
           AND INDEX_NAME='PRIMARY')                          AS primary_key_columns
  FROM information_schema.COLUMNS
 WHERE TABLE_SCHEMA = 'indiv_cust' AND TABLE_NAME = 'L_INDVCST_LABEL';

-- ----------------------------------------------------------------------------
-- 2. 码值总量与字段覆盖
--    期望：code_rows = 1723；tag_fields = 177
-- ----------------------------------------------------------------------------
SELECT COUNT(*)                    AS code_rows,
       COUNT(DISTINCT tag_name_en) AS tag_fields,
       COUNT(DISTINCT tag_code)    AS distinct_codes
  FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP`;

-- 2b. 按字段的码值条数分布（查看是否有字段码值过少）
SELECT code_count AS codes_per_field, COUNT(*) AS field_count
  FROM (SELECT tag_name_en, COUNT(*) AS code_count
          FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` GROUP BY tag_name_en) t
 GROUP BY code_count ORDER BY code_count;

-- ----------------------------------------------------------------------------
-- 3. 重复码值：同一字段下码值重复（主键缺失或异常时才会返回行）
--    期望：0 行
-- ----------------------------------------------------------------------------
SELECT tag_name_en, tag_code, COUNT(*) AS dup_count
  FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP`
 GROUP BY tag_name_en, tag_code
HAVING COUNT(*) > 1;

-- ----------------------------------------------------------------------------
-- 4. 孤立码值：码表中的 tag_name_en 在宽表里不存在对应列
--    期望：0 行
-- ----------------------------------------------------------------------------
SELECT DISTINCT c.tag_name_en
  FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` c
  LEFT JOIN information_schema.COLUMNS col
         ON col.TABLE_SCHEMA = 'indiv_cust'
        AND col.TABLE_NAME   = 'L_INDVCST_LABEL'
        AND col.COLUMN_NAME  = c.tag_name_en
 WHERE col.COLUMN_NAME IS NULL;

-- ----------------------------------------------------------------------------
-- 5. 缺失码值：应配码值的 177 个字段中，码表里没有记录的
--    期望：0 行
-- ----------------------------------------------------------------------------
SELECT e.tag_name_en AS missing_code_field
  FROM (
      SELECT 'ACCT_OPENING_LEVEL1_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'ACCT_OPENING_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_AML_BLACKLIST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_APP_DEVICE_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BENEFIT_VALUE_ACCT_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BENEFIT_VALUE_ACTIVATION_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_A_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CARE_CUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CASH_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL1_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL3_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_LEVEL_SMART_SUSPEND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_EXCLUSIVE_MEMBER_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_B_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FUND_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FUND_SIP_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ACCT_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ANNUITY_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CC_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CLASS_1_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_DIY_DEBIT_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_EASY_FINANCE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_ACCUMULATION_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_LEVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_HEALTH_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PLEDGE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRESTIGE_CARD_A_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRESTIGE_CARD_B_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRIVATE_BANK_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_RESERVE_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_SS_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_SUPREME_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TIME_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TREASURY_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TRUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_DIRECT_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_PP_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_TEACHER_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_YOUTH_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VIP_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_INSURANCE_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MARKETING_BLACKLIST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_BANKING_OPENED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_DIGIT_STANDARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_NUMBER_NORMAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_EMPLOYEE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_LOAN_OVERDUE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_A_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_B_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_TYPE_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_CUST_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_VIP_POTENTIAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PERS_LOAN_PROMOTER_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_TO_DORMANT_ACCT_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_TO_SMART_SUSPEND_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_PROMOTER_VALID_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_REFERRAL_M1_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_REFERRAL_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_AUTH_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_GROUP_JOINED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WMP_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_LINK_PAYROLL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022' AS tag_name_en
    UNION ALL
      SELECT 'DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'GENDER' AS tag_name_en
    UNION ALL
      SELECT 'HIGHEST_EDUCATION' AS tag_name_en
    UNION ALL
      SELECT 'HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CASH_MGMT_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CC_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_FX_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_OTC_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PAY_LOAN_A_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PAY_LOAN_B_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PRESTIGE_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TIME_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TREASURY_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_MAX_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_SALARY_LINK_PAYROLL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_WECOM_FRIEND_ADDED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HOUSEHOLD_ANNUAL_INCOME_PB_KYC' AS tag_name_en
    UNION ALL
      SELECT 'HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT' AS tag_name_en
    UNION ALL
      SELECT 'ID_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT' AS tag_name_en
    UNION ALL
      SELECT 'LAST_12_MONTHS_LARGE_TRANSFER_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LATEST_CIR_EMPLOYMENT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_OPS_KYC' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_PB_KYC' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_WAN_KYC' AS tag_name_en
    UNION ALL
      SELECT 'PREV_12_MONTHS_MAX_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG' AS tag_name_en
       ) e
  LEFT JOIN `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` c ON c.tag_name_en = e.tag_name_en
 WHERE c.tag_name_en IS NULL;

-- ----------------------------------------------------------------------------
-- 6. 布尔标签覆盖率：129 个布尔字段是否都有码值，且每字段恰好 2 条 (0/1)
--    期望：covered = 129；缺码值 0 行；异常 0 行
-- ----------------------------------------------------------------------------
-- 6a. 覆盖数与缺失清单
SELECT COUNT(*) AS bool_expected,
       SUM(CASE WHEN c.tag_name_en IS NOT NULL THEN 1 ELSE 0 END) AS bool_covered
  FROM (
      SELECT 'CUR_AML_BLACKLIST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BENEFIT_VALUE_ACTIVATION_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CARE_CUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CASH_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_LEVEL_SMART_SUSPEND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ACCT_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ANNUITY_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CC_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CLASS_1_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_DIY_DEBIT_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_EASY_FINANCE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_ACCUMULATION_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_LEVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_HEALTH_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PLEDGE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRESTIGE_CARD_A_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRESTIGE_CARD_B_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRIVATE_BANK_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_RESERVE_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_SS_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_SUPREME_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TIME_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TREASURY_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TRUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_DIRECT_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_PP_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_TEACHER_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_YOUTH_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VIP_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MARKETING_BLACKLIST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_BANKING_OPENED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_DIGIT_STANDARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_NUMBER_NORMAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_EMPLOYEE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_LOAN_OVERDUE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_VIP_POTENTIAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PERS_LOAN_PROMOTER_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_TO_DORMANT_ACCT_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_TO_SMART_SUSPEND_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_PROMOTER_VALID_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_REFERRAL_M1_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_REFERRAL_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_AUTH_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_GROUP_JOINED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_LINK_PAYROLL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022' AS tag_name_en
    UNION ALL
      SELECT 'DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CASH_MGMT_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CC_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_FX_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_OTC_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PAY_LOAN_A_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PAY_LOAN_B_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PRESTIGE_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TIME_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TREASURY_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_SALARY_LINK_PAYROLL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_WECOM_FRIEND_ADDED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_12_MONTHS_LARGE_TRANSFER_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG' AS tag_name_en
       ) e
  LEFT JOIN (SELECT DISTINCT tag_name_en FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP`) c
         ON c.tag_name_en = e.tag_name_en;

-- 6b. 布尔字段码值异常（条数不为 2，或码值集合不为 '0,1'）
--     期望：0 行
SELECT e.tag_name_en,
       COUNT(c.tag_code)                                     AS code_count,
       GROUP_CONCAT(c.tag_code ORDER BY c.tag_code)           AS code_values
  FROM (
      SELECT 'CUR_AML_BLACKLIST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BENEFIT_VALUE_ACTIVATION_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CARE_CUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CASH_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CASH_ASSET_UNDER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CC_POTENTIAL_CUST_FLAG_CUST_LEVEL_PREDICTION' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORPORATE_CREDIT_LISTED_ENT_LEGAL_PERSON_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_LEVEL_SMART_SUSPEND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_EQUITY_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FIXED_INCOME_ASSET_OVER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FIXED_INCOME_ASSET_UNDER_ALLOCATED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ACCT_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ANNUITY_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_BRANCH_SAVINGS_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CC_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CLASSIC_LEVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CLASS_1_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_DIY_DEBIT_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_EASY_FINANCE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_FIXED_GOLD_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_ACCUMULATION_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_GOLD_LEVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_HEALTH_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_LOCAL_DISTRICT_SUB_BRANCH_SAVINGS_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NORMAL_CONVENIENT_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NORMAL_SNAKE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_DRAGON_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_HORSE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_NOT_ACTIVATED_SS_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_A_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_B_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_C_TYPE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PAY_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_ONLINE_PRESTIGE_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PLEDGE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRESTIGE_CARD_A_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRESTIGE_CARD_B_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PRIVATE_BANK_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_PROTECTION_PROPERTY_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_RESERVE_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_SS_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_SUPREME_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TIME_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TREASURY_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_TRUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_UNIVERSAL_LIFE_INSURANCE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_BUSINESS_TRAVEL_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_CONSTELLATION_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_CO_BRANDED_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_DIRECT_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_DRAGON_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_HORSE_YEAR_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_PP_ACCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_SPORTS_BENEFIT_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_TEACHER_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VALID_YOUTH_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_VIP_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WEALTH_DIAMOND_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WEALTH_PLATINUM_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_HOLDING_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MARKETING_BLACKLIST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_BANKING_OPENED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_DIGIT_STANDARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MOBILE_NUMBER_NORMAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_MONTH_FUND_RECEIPT_PAYMENT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_CREDIT_STATUS_NORMAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_EMPLOYEE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_OUR_BANK_LOAN_OVERDUE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_AND_CREDIT_CORE_CHANNEL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_AND_WEALTH_CORE_CHANNEL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_ASSET_ALLOCATION_REACH_TARGET_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_VIP_POTENTIAL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PERS_LOAN_PROMOTER_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_POTENTIAL_PRIVATE_DIAMOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_TO_DORMANT_ACCT_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_TO_SMART_SUSPEND_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WARNING_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_PROMOTER_VALID_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_REFERRAL_M1_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_REFERRAL_M2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_AUTH_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_FRIEND_ADDED_FLAG_PERS_LOAN' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_GROUP_JOINED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WECOM_SESSION_ARCHIVE_AUTH_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_LINK_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_LINK_PAYROLL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_NEW_PAYROLL_VALID_CUST_FLAG_Y2024' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_SALARY_TREASURE_2_VALID_CUST_FLAG_Y2022' AS tag_name_en
    UNION ALL
      SELECT 'DO_NOT_DISTURB_CUST_WECOM_TAG_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ALLOCATED_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_BUSINESS_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CASH_MGMT_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CC_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_CONSUMER_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_FUND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_FX_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_GOLD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAYROLL_TAX_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_CHANNEL_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_ONLINE_PAY_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_OTC_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PAY_LOAN_A_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PAY_LOAN_B_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_PRESTIGE_CARD_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TIME_DEPOSIT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TRADE_LOAN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_TREASURY_BOND_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_VILLAGER_BUSINESS_LINK_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_HOLDING_WMP_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_QUALIFIED_INVESTOR_CERTIFICATION_COMPLETE_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_SALARY_LINK_FIRST_PAYROLL_PRODUCT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_SALARY_LINK_PAYROLL_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'HIST_WECOM_FRIEND_ADDED_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_12_MONTHS_LARGE_TRANSFER_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_30_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_30_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_7_DAYS_DIFF_NAME_INTERBANK_TRANSFER_IN_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'LAST_7_DAYS_SAME_NAME_INTERBANK_TRANSFER_OUT_FLAG' AS tag_name_en
    UNION ALL
      SELECT 'REGISTERED_RESIDENCE_WHETHER_OUR_BANK_BUSINESS_AREA_FLAG' AS tag_name_en
       ) e
  LEFT JOIN `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` c ON c.tag_name_en = e.tag_name_en
 GROUP BY e.tag_name_en
HAVING code_count <> 2 OR code_values <> '0,1';

-- ----------------------------------------------------------------------------
-- 7. 选项标签覆盖率：48 个选项字段是否都有码值，且每字段 >= 2 条
--    期望：45(=48) 全覆盖；异常 0 行
-- ----------------------------------------------------------------------------
-- 7a. 覆盖数与缺失清单
SELECT COUNT(*) AS option_expected,
       SUM(CASE WHEN c.tag_name_en IS NOT NULL THEN 1 ELSE 0 END) AS option_covered
  FROM (
      SELECT 'ACCT_OPENING_LEVEL1_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'ACCT_OPENING_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_APP_DEVICE_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BENEFIT_VALUE_ACCT_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_A_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL1_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL3_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_EXCLUSIVE_MEMBER_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_B_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FUND_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FUND_SIP_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_INSURANCE_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_A_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_B_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_TYPE_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_CUST_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WMP_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY' AS tag_name_en
    UNION ALL
      SELECT 'GENDER' AS tag_name_en
    UNION ALL
      SELECT 'HIGHEST_EDUCATION' AS tag_name_en
    UNION ALL
      SELECT 'HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'HIST_MAX_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'HOUSEHOLD_ANNUAL_INCOME_PB_KYC' AS tag_name_en
    UNION ALL
      SELECT 'HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT' AS tag_name_en
    UNION ALL
      SELECT 'ID_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT' AS tag_name_en
    UNION ALL
      SELECT 'LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LATEST_CIR_EMPLOYMENT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_OPS_KYC' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_PB_KYC' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_WAN_KYC' AS tag_name_en
    UNION ALL
      SELECT 'PREV_12_MONTHS_MAX_CUST_LEVEL' AS tag_name_en
       ) e
  LEFT JOIN (SELECT DISTINCT tag_name_en FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP`) c
         ON c.tag_name_en = e.tag_name_en;

-- 7b. 选项字段码值不足 2 条的字段
--     期望：0 行
SELECT e.tag_name_en, COUNT(c.tag_code) AS code_count
  FROM (
      SELECT 'ACCT_OPENING_LEVEL1_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'ACCT_OPENING_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_APP_DEVICE_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_ASSET_POTENTIAL_LEVEL_RULE_PREDICTION' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BENEFIT_VALUE_ACCT_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_A_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_CREDIT_LINE_FREEZE_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_BUSINESS_LINK_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL1_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CORE_CM_LEVEL3_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_POTENTIAL_LEVEL_WEALTH_VALUE_POTENTIAL_MODEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_CUST_UPGRADE_TO_GOLD_KEY_FOLLOW_UP_EMPLOYEE_HR_LINE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_EXCLUSIVE_MEMBER_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_B_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_CREDIT_LINE_FREEZE_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FAST_LOAN_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FUND_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_FUND_SIP_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_INSURANCE_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_A_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_B_CARD_RATING' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PAY_LOAN_TYPE_CREDIT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_CUST_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_PRE_TAX_AVG_MONTHLY_INCOME_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NEW_REPEAT_LOYAL_CLASS_Y2026' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WEALTH_NON_INSURANCE_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_WMP_RISK_ASSESSMENT_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'CUR_YEAR_MAX_WEALTH_INCOME_PRODUCT_CATEGORY' AS tag_name_en
    UNION ALL
      SELECT 'GENDER' AS tag_name_en
    UNION ALL
      SELECT 'HIGHEST_EDUCATION' AS tag_name_en
    UNION ALL
      SELECT 'HIST_BUSINESS_LATEST_ASSOCIATED_MARKETER_AFFIL_LEVEL2_BRANCH' AS tag_name_en
    UNION ALL
      SELECT 'HIST_MAX_CUST_LEVEL' AS tag_name_en
    UNION ALL
      SELECT 'HOUSEHOLD_ANNUAL_INCOME_PB_KYC' AS tag_name_en
    UNION ALL
      SELECT 'HOUSEHOLD_TOTAL_ASSET_WMP_RISK_ASSESSMENT' AS tag_name_en
    UNION ALL
      SELECT 'ID_TYPE' AS tag_name_en
    UNION ALL
      SELECT 'INVESTMENT_EXPERIENCE_WMP_RISK_ASSESSMENT' AS tag_name_en
    UNION ALL
      SELECT 'LAST_MONTH_END_PB_MAIN_ACCT_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LAST_MONTH_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LAST_YEAR_END_WEALTH_NEW_REPEAT_LOYAL_CLASS' AS tag_name_en
    UNION ALL
      SELECT 'LATEST_CIR_EMPLOYMENT_STATUS' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_OPS_KYC' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_PB_KYC' AS tag_name_en
    UNION ALL
      SELECT 'OUTSIDE_ASSET_WAN_KYC' AS tag_name_en
    UNION ALL
      SELECT 'PREV_12_MONTHS_MAX_CUST_LEVEL' AS tag_name_en
       ) e
  LEFT JOIN `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` c ON c.tag_name_en = e.tag_name_en
 GROUP BY e.tag_name_en
HAVING code_count < 2;

-- ----------------------------------------------------------------------------
-- 8. 码值质量：空值 / code_sort 异常 / 码值超长
--    期望：全部 0
-- ----------------------------------------------------------------------------
SELECT SUM(tag_code = '' OR tag_code IS NULL)          AS empty_tag_code,
       SUM(tag_code <> TRIM(tag_code))                 AS tag_code_with_spaces,
       SUM(code_definition IS NULL OR code_definition = '') AS empty_code_definition,
       SUM(tag_name_cn IS NULL OR tag_name_cn = '')    AS empty_tag_name_cn,
       SUM(code_sort IS NULL OR code_sort < 1)         AS bad_code_sort,
       SUM(CHAR_LENGTH(tag_name_en) > 64)              AS tag_name_en_over_64
  FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP`;

-- ----------------------------------------------------------------------------
-- 9. code_sort 是否从 1 开始连续（排序号连续性体检）
--    期望：0 行
-- ----------------------------------------------------------------------------
SELECT tag_name_en, COUNT(*) AS n, MIN(code_sort) AS min_sort, MAX(code_sort) AS max_sort
  FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP`
 GROUP BY tag_name_en
HAVING MIN(code_sort) <> 1 OR MAX(code_sort) <> COUNT(*);

-- ----------------------------------------------------------------------------
-- 10. 宽表数据体检（导入客户数据后执行）：主键空值 / 主键重复
--     期望：0 / 0
-- ----------------------------------------------------------------------------
SELECT SUM(CUST_ID IS NULL OR CUST_ID = '') AS null_cust_id,
       COUNT(*) - COUNT(DISTINCT CUST_ID)   AS dup_cust_id
  FROM `indiv_cust`.`L_INDVCST_LABEL`;

-- ----------------------------------------------------------------------------
-- 11. 码值 ↔ 宽表抽样对账（查看某字段的码值与宽表取值域是否吻合）
--     把 'GENDER' 换成任意选项型/布尔型字段名即可复用
-- ----------------------------------------------------------------------------
SELECT c.tag_code, c.code_definition, c.code_sort,
       COUNT(t.CUST_ID) AS customer_rows
  FROM `indiv_cust`.`L_INDVCST_LABEL_CODE_MAP` c
  LEFT JOIN `indiv_cust`.`L_INDVCST_LABEL` t ON t.GENDER = c.tag_code
 WHERE c.tag_name_en = 'GENDER'
 GROUP BY c.tag_code, c.code_definition, c.code_sort
 ORDER BY c.code_sort;

-- ============================================================================
-- 执行提示：本脚本逐段返回结果集，请人工核对每段的『期望』注释。
-- 若某段返回非空异常清单，请先处理再投入评测使用。
-- ============================================================================